"""Road understanding package — Phase 2 (Module 03).

Module 2A: config / verify_setup / model paths
Module 2B: DeepLabV3+ BDD100K road segmentation
Module 2C: YOLO road-object detection + ByteTrack persistent IDs
Module 2D: pretrained MiDaS relative depth + calibrated track distances
Module 2E: HSV traffic-light state classification
Module 2F: Caltech YOLO-LSTM temporal pedestrian localization
Module 2G: unified stateful frame pipeline
Module 2H: REST/WebSocket API integration (apps/backend)
Module 2I: road-understanding UI
"""

from ml.road_understanding.config import (
    COCO_ROAD_CLASS_IDS,
    DEPTH_MAX_DISTANCE_M,
    DEPTH_METERS_OFFSET,
    DEPTH_METERS_SCALE,
    DEPTH_ROI_INSET_RATIO,
    MIDAS_MODEL_TYPE,
    MIDAS_REPOSITORY,
    MODELS_DIR,
    PEDESTRIAN_TEMPORAL_CONFIDENCE,
    PEDESTRIAN_TEMPORAL_INPUT_SIZE,
    PEDESTRIAN_TEMPORAL_MODEL_PATH,
    PEDESTRIAN_TEMPORAL_SEQUENCE_LENGTH,
    ROAD_CLASS_NAMES,
    SEG_ROAD_BACKGROUND_CLASS_ID,
    SEG_ROAD_CLASS_COLORS_BGR,
    SEG_ROAD_CLASS_NAMES,
    SEG_ROAD_INPUT_SIZE,
    SEG_ROAD_MODEL_PATH,
    SEG_ROAD_OVERLAY_ALPHA,
    TRACK_ACTIVATION_THRESHOLD,
    TRACK_FRAME_RATE,
    TRACK_IOU_THRESHOLD,
    TRACK_MAX_AGE,
    TRACK_MIN_HITS,
    TRACK_MINIMUM_MATCHING_THRESHOLD,
    TRAFFIC_LIGHT_MIN_CROP_PX,
    TRAFFIC_LIGHT_STATES,
    YOLO_ROAD_CONFIDENCE,
    YOLO_ROAD_FALLBACK_MODEL,
    YOLO_ROAD_MODEL_PATH,
    ensure_models_dir,
    pedestrian_temporal_model_ready,
    resolve_yolo_road_weights,
    seg_road_model_ready,
    yolo_road_model_ready,
)
from ml.road_understanding.depth_estimator import (
    DepthCalibration,
    DepthMap,
    MiDaSDepthEstimator,
    ObjectDepthEstimate,
    RoadDepthResult,
    depth_estimator_loaded,
    estimate_depth,
    estimate_track_depths,
    annotate_track_depths,
    get_depth_estimator,
    sample_bbox_inverse_depth,
)
from ml.road_understanding.object_detector import (
    RoadDetection,
    RoadDetections,
    YOLORoadDetector,
    detect_road_objects,
    get_road_detector,
)
from ml.road_understanding.pedestrian_temporal import (
    PedestrianTemporalLocalization,
    TemporalPedestrianLocalizer,
    build_temporal_model,
    get_temporal_pedestrian_localizer,
    localize_primary_pedestrian,
)
from ml.road_understanding.road_segmenter import (
    RoadSegmentation,
    RoadSegmenter,
    get_road_segmenter,
    segment_road,
)
from ml.road_understanding.tracker import (
    RoadObjectTracker,
    RoadTracks,
    TrackedRoadObject,
    detect_and_track_road_objects,
    format_track_id,
    get_road_tracker,
    track_road_objects,
)
from ml.road_understanding.traffic_light import (
    TrafficLightClassification,
    TrafficLightClassifier,
    TrafficLightResults,
    annotate_traffic_light_states,
    classify_traffic_lights,
    get_traffic_light_classifier,
)
from ml.road_understanding.pipeline import (
    RoadPipelineOptions,
    RoadPipelineResult,
    RoadUnderstandingPipeline,
    get_road_pipeline,
    process_road_frame,
)

__all__ = [
    "MODELS_DIR",
    "SEG_ROAD_MODEL_PATH",
    "SEG_ROAD_INPUT_SIZE",
    "SEG_ROAD_CLASS_NAMES",
    "SEG_ROAD_CLASS_COLORS_BGR",
    "SEG_ROAD_BACKGROUND_CLASS_ID",
    "SEG_ROAD_OVERLAY_ALPHA",
    "YOLO_ROAD_MODEL_PATH",
    "YOLO_ROAD_FALLBACK_MODEL",
    "PEDESTRIAN_TEMPORAL_MODEL_PATH",
    "PEDESTRIAN_TEMPORAL_SEQUENCE_LENGTH",
    "PEDESTRIAN_TEMPORAL_INPUT_SIZE",
    "PEDESTRIAN_TEMPORAL_CONFIDENCE",
    "MIDAS_REPOSITORY",
    "MIDAS_MODEL_TYPE",
    "DEPTH_METERS_SCALE",
    "DEPTH_METERS_OFFSET",
    "DEPTH_ROI_INSET_RATIO",
    "DEPTH_MAX_DISTANCE_M",
    "ROAD_CLASS_NAMES",
    "COCO_ROAD_CLASS_IDS",
    "YOLO_ROAD_CONFIDENCE",
    "TRACK_ACTIVATION_THRESHOLD",
    "TRACK_MAX_AGE",
    "TRACK_MIN_HITS",
    "TRACK_MINIMUM_MATCHING_THRESHOLD",
    "TRACK_FRAME_RATE",
    "TRACK_IOU_THRESHOLD",
    "TRAFFIC_LIGHT_MIN_CROP_PX",
    "TRAFFIC_LIGHT_STATES",
    "ensure_models_dir",
    "seg_road_model_ready",
    "yolo_road_model_ready",
    "pedestrian_temporal_model_ready",
    "resolve_yolo_road_weights",
    "RoadDetection",
    "RoadDetections",
    "YOLORoadDetector",
    "get_road_detector",
    "detect_road_objects",
    "RoadSegmentation",
    "RoadSegmenter",
    "get_road_segmenter",
    "segment_road",
    "TrackedRoadObject",
    "RoadTracks",
    "RoadObjectTracker",
    "format_track_id",
    "get_road_tracker",
    "track_road_objects",
    "detect_and_track_road_objects",
    "DepthCalibration",
    "DepthMap",
    "ObjectDepthEstimate",
    "RoadDepthResult",
    "MiDaSDepthEstimator",
    "sample_bbox_inverse_depth",
    "depth_estimator_loaded",
    "get_depth_estimator",
    "estimate_depth",
    "estimate_track_depths",
    "annotate_track_depths",
    "TrafficLightClassification",
    "TrafficLightResults",
    "TrafficLightClassifier",
    "get_traffic_light_classifier",
    "classify_traffic_lights",
    "annotate_traffic_light_states",
    "PedestrianTemporalLocalization",
    "TemporalPedestrianLocalizer",
    "build_temporal_model",
    "get_temporal_pedestrian_localizer",
    "localize_primary_pedestrian",
    "RoadPipelineOptions",
    "RoadPipelineResult",
    "RoadUnderstandingPipeline",
    "get_road_pipeline",
    "process_road_frame",
]
