"""Public API for the Phase 4 risk engine."""

from ml.risk_engine.aggregator import (
    AGGRESSIVE_RELATIVE_SPEED_THRESHOLD_KMH,
    PEDESTRIAN_DISTANCE_THRESHOLD_M,
    RISK_LEVELS,
    RISK_WEIGHTS,
    RiskFactor,
    RiskResult,
    compute_risk,
    risk_level,
)
from ml.risk_engine.event_detector import (
    DEFAULT_FPS,
    DRIVER_ASLEEP_DROWSY_FRAMES,
    HARD_BRAKING_DECEL_KMH_PER_S,
    MIN_CLOSING_SPEED_KMH,
    NEAR_COLLISION_TTC_SECONDS,
    PEDESTRIAN_HAZARD_DISTANCE_M,
    PROLONGED_PHONE_SECONDS,
    UNSAFE_FOLLOWING_MIN_SPEED_KMH,
    UNSAFE_FOLLOWING_TTC_SECONDS,
    EventDetectionResult,
    EventDetector,
    SafetyEvent,
    compute_ttc_seconds,
    detect_events,
)
from ml.risk_engine.explanations import explain_safety_event, explanation_method
from ml.risk_engine.rules import (
    DEFAULT_RULES_PATH,
    AppliedOverride,
    OverrideRule,
    RiskDecision,
    RuleCondition,
    apply_overrides,
    compute_risk_with_overrides,
    load_rules,
)

__all__ = [
    "AGGRESSIVE_RELATIVE_SPEED_THRESHOLD_KMH",
    "PEDESTRIAN_DISTANCE_THRESHOLD_M",
    "RISK_LEVELS",
    "RISK_WEIGHTS",
    "RiskFactor",
    "RiskResult",
    "compute_risk",
    "risk_level",
    "DEFAULT_RULES_PATH",
    "AppliedOverride",
    "OverrideRule",
    "RiskDecision",
    "RuleCondition",
    "apply_overrides",
    "compute_risk_with_overrides",
    "load_rules",
    "DEFAULT_FPS",
    "DRIVER_ASLEEP_DROWSY_FRAMES",
    "HARD_BRAKING_DECEL_KMH_PER_S",
    "MIN_CLOSING_SPEED_KMH",
    "NEAR_COLLISION_TTC_SECONDS",
    "PEDESTRIAN_HAZARD_DISTANCE_M",
    "PROLONGED_PHONE_SECONDS",
    "UNSAFE_FOLLOWING_MIN_SPEED_KMH",
    "UNSAFE_FOLLOWING_TTC_SECONDS",
    "EventDetectionResult",
    "EventDetector",
    "SafetyEvent",
    "compute_ttc_seconds",
    "detect_events",
    "explain_safety_event",
    "explanation_method",
]
