"""API v1 route package — routers are registered in app.main."""

from app.api.v1 import (
    admin,
    analytics,
    assistant,
    auth,
    cabin,
    demo,
    driver,
    events,
    fleet,
    industry,
    kuksa,
    maintenance,
    media,
    ml_gov,
    models,
    notifications,
    orgs,
    risk,
    road,
    telemetry,
    users,
    ws,
    xai,
)

ALL_ROUTERS = [
    auth.router,
    orgs.router,
    users.router,
    admin.router,
    models.router,
    ml_gov.router,
    notifications.router,
    industry.router,
    media.router,
    cabin.router,
    driver.router,
    road.router,
    risk.router,
    maintenance.router,
    assistant.router,
    fleet.router,
    events.router,
    telemetry.router,
    analytics.router,
    xai.router,
    ws.router,
    demo.router,
    kuksa.router,
]
